from typing import Protocol, Iterable, Optional
from .domain import User

class UserRepository(Protocol):
    def next_id(self) -> int: ...
    def add(self, user: User) -> None: ...
    def list_all(self) -> Iterable[User]: ...
    def get_by_id(self, user_id: int) -> Optional[User]: ...
    def save(self, user: User) -> None: ...

class EmailSender(Protocol):
    def send(self, to_email: str, message: str) -> None: ...

class ExternalUserApi(Protocol):
    def get_user(self, user_id: int) -> Optional[dict]: ...